### ISSUE TITLE
Timezone support

### ISSUE THREAD

**Issue by chr1s-b** [lekro/elosensei#12]
Modify user inputs to prevent timezone issues that could result in creating matches out of order. Store timestamps in the database through one centralised timezone (something like UTC or GMT)

**Comment by lekro** [comment]
I believe this is already being done. In the footer, Discord appears to automatically convert UTC timestamps into local time. 

What I would really like is if it were possible to get the invoking user's timezone so necessary adjustments could be performed on manually entered match times. But unfortunately timezones also change with time, so forcing users to use UTC may be the best idea in the long run... (When we "get another hour" here, I think 1am repeata twice.)
