### ISSUE TITLE
Sanitize user ids

### ISSUE THREAD

**Issue by lekro** [lekro/elosensei#2]
Currently we allow arbitrary user IDs to become players, by sending `elo! match 1 win 2 loss`. But this doesn't make sense in production. So this has to be disabled after testing.

**Comment by Parallax-Vector** [comment]
For reference, the ! is no longer required to seperate arguments.

**Comment by chr1s-b** [comment]
Make solution conditional depending on a JSON property `debug` ?

**Comment by lekro** [comment]
That sounds like a good idea.

**Comment by lekro** [comment]
This was done with the move to discord.py converters.
